name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.3
      - name: Install tools
        run: ./script/install.sh
        continue-on-error: false
      - name: Download source
        run: ./script/download.sh 3.3.3 gerrit; cp -r plugins/* gerrit/plugins/
        continue-on-error: false
      - name: Build plugins
        run: ./script/build.sh gerrit plugins 3.3.3
        continue-on-error: false
